// <auto-generated />
using System;
using GestaoEventos.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestaoEventos.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240804234121_AdicionadoIngresso")]
    partial class AdicionadoIngresso
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("GestaoEventos.Domain.Eventos.Evento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("eventos", (string)null);
                });

            modelBuilder.Entity("GestaoEventos.Domain.Eventos.Evento", b =>
                {
                    b.OwnsOne("GestaoEventos.Domain.Eventos.DetalhesEvento", "Detalhes", b1 =>
                        {
                            b1.Property<Guid>("EventoId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("CapacidadeMaxima")
                                .HasColumnType("INTEGER")
                                .HasColumnName("capacidade_maxima");

                            b1.Property<DateTime>("DataHora")
                                .HasColumnType("TEXT")
                                .HasColumnName("data_hora");

                            b1.Property<string>("Localizacao")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("localizacao");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("nome");

                            b1.Property<int>("Status")
                                .HasColumnType("INTEGER")
                                .HasColumnName("status");

                            b1.HasKey("EventoId");

                            b1.ToTable("eventos");

                            b1.WithOwner()
                                .HasForeignKey("EventoId");
                        });

                    b.OwnsMany("GestaoEventos.Domain.Eventos.Ingresso", "Ingressos", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT")
                                .HasColumnName("id");

                            b1.Property<Guid>("EventoId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Preco")
                                .HasPrecision(8, 2)
                                .HasColumnType("TEXT")
                                .HasColumnName("preco");

                            b1.Property<int>("Quantidade")
                                .HasColumnType("INTEGER")
                                .HasColumnName("quantidade");

                            b1.HasKey("Id");

                            b1.HasIndex("EventoId");

                            b1.ToTable("eventos_ingressos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("EventoId");

                            b1.OwnsOne("GestaoEventos.Domain.Eventos.TipoIngresso", "Tipo", b2 =>
                                {
                                    b2.Property<Guid>("IngressoId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Descricao")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("descricao");

                                    b2.Property<string>("Nome")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("nome");

                                    b2.HasKey("IngressoId");

                                    b2.ToTable("eventos_ingressos");

                                    b2.WithOwner()
                                        .HasForeignKey("IngressoId");
                                });

                            b1.Navigation("Tipo")
                                .IsRequired();
                        });

                    b.Navigation("Detalhes")
                        .IsRequired();

                    b.Navigation("Ingressos");
                });
#pragma warning restore 612, 618
        }
    }
}
