version: "3.8"

name: gestao-eventos

services:
  postgres:
    image: postgres
    container_name: postgres_gestao_eventos
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: MinhaS3nh@
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80

volumes:
  postgres_data:
