// <auto-generated />
using System;
using EventFlow.Compras.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventFlow.Compras.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ComprasDbContext))]
    [Migration("20251203033906_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventFlow.Compras.Domain.CompraIngresso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataHoraCompra")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_hora_compra");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("usuario_id");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_total");

                    b.HasKey("Id");

                    b.ToTable("compra_ingresos", (string)null);
                });

            modelBuilder.Entity("EventFlow.Compras.Domain.CompraIngresso", b =>
                {
                    b.OwnsMany("EventFlow.Compras.Domain.ItemCompra", "Itens", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("IngressoId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("ingresso_id");

                            b1.Property<decimal>("PrecoUnitario")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("preco_unitario");

                            b1.Property<int>("Quantidade")
                                .HasColumnType("int")
                                .HasColumnName("quantidade");

                            b1.Property<Guid>("compra_ingressos_id")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("compra_ingressos_id");

                            b1.ToTable("compra_ingresos_itens", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("compra_ingressos_id");
                        });

                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
