// <auto-generated />
using System;
using GestaoEventos.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestaoEventos.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240802030859_AdicionadoStatusEvento")]
    partial class AdicionadoStatusEvento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("GestaoEventos.Domain.Eventos.Evento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("eventos", (string)null);
                });

            modelBuilder.Entity("GestaoEventos.Domain.Eventos.Evento", b =>
                {
                    b.OwnsOne("GestaoEventos.Domain.Eventos.DetalhesEvento", "Detalhes", b1 =>
                        {
                            b1.Property<Guid>("EventoId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("CapacidadeMaxima")
                                .HasColumnType("INTEGER")
                                .HasColumnName("capacidade_maxima");

                            b1.Property<DateTime>("DataHora")
                                .HasColumnType("TEXT")
                                .HasColumnName("data_hora");

                            b1.Property<string>("Localizacao")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("localizacao");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("nome");

                            b1.Property<int>("Status")
                                .HasColumnType("INTEGER")
                                .HasColumnName("status");

                            b1.HasKey("EventoId");

                            b1.ToTable("eventos");

                            b1.WithOwner()
                                .HasForeignKey("EventoId");
                        });

                    b.Navigation("Detalhes")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
